export const TimeLineData = [
    { 
        id: 1,
        title: "Titre",
        location: "Paris, France",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'work', 
    },
    { 
        id: 2,
        title: "Titre 2",
        location: "Paris, France",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'work', 
    },
    { 
        id: 3,
        title: "Titre 3",
        location: "Paris, France",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'school', 
    },
    { 
        id: 4,
        title: "Titre 4",
        location: "Paris, France",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'work', 
    },
    { 
        id: 5,
        title: "Titre 5",
        location: "Paris, France",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        buttonText: "Bouton",
        date: "Février 2016 - Aujourd'hui", 
        icon: 'school', 
    },
  ];